export const apiErrorCodes = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_ABORTED: 'UPLOAD_ABORTED',
  UPLOAD_IDLE_TIMEOUT: 'UPLOAD_IDLE_TIMEOUT',
  UPLOAD_HARD_TIMEOUT: 'UPLOAD_HARD_TIMEOUT',
  INVALID_FILE_PATH: 'INVALID_FILE_PATH',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  FILE_READ_FAILED: 'FILE_READ_FAILED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PARENT_NOT_FOUND: 'PARENT_NOT_FOUND',
  PARENT_SCOPE_FORBIDDEN: 'PARENT_SCOPE_FORBIDDEN',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',
  SELF_ACTION_FORBIDDEN: 'SELF_ACTION_FORBIDDEN',
  PRIMARY_ADMIN_PROTECTED: 'PRIMARY_ADMIN_PROTECTED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  EXPORT_FORMAT_INVALID: 'EXPORT_FORMAT_INVALID',
  REPORT_EXPORT_FAILED: 'REPORT_EXPORT_FAILED',
  INIT_DISABLED: 'INIT_DISABLED',
  INIT_TOKEN_INVALID: 'INIT_TOKEN_INVALID',
  INIT_CONFIG_MISSING: 'INIT_CONFIG_MISSING',
  INIT_PASSWORD_WEAK: 'INIT_PASSWORD_WEAK',
  CUSTOMER_DUPLICATE: 'CUSTOMER_DUPLICATE',
  CUSTOMER_SCOPE_FORBIDDEN: 'CUSTOMER_SCOPE_FORBIDDEN',
  IMPORT_EMPTY_FILE: 'IMPORT_EMPTY_FILE',
  IMPORT_TEMPLATE_INVALID: 'IMPORT_TEMPLATE_INVALID',
  NO_IMPORT_ROWS: 'NO_IMPORT_ROWS',
  INVALID_ACTION: 'INVALID_ACTION',
  INVALID_TARGET_TYPE: 'INVALID_TARGET_TYPE',
  DELETION_NOT_ALLOWED: 'DELETION_NOT_ALLOWED',
  DELETION_REQUEST_EXISTS: 'DELETION_REQUEST_EXISTS',
  DELETION_REQUEST_NOT_FOUND: 'DELETION_REQUEST_NOT_FOUND',
  DELETION_REQUEST_ALREADY_PROCESSED: 'DELETION_REQUEST_ALREADY_PROCESSED',
  DELETION_REQUEST_STATE_CHANGED: 'DELETION_REQUEST_STATE_CHANGED',
  RECEIPT_EDIT_TRANSFER_REVERSAL_REQUIRED: 'RECEIPT_EDIT_TRANSFER_REVERSAL_REQUIRED',
  EXCEL_TOKEN_REQUIRED: 'EXCEL_TOKEN_REQUIRED',
  EXCEL_TOKEN_INVALID: 'EXCEL_TOKEN_INVALID',
  EXCEL_TOKEN_REVOKED: 'EXCEL_TOKEN_REVOKED',
  EXCEL_TOKEN_EXPIRED: 'EXCEL_TOKEN_EXPIRED',
  EXCEL_TOKEN_NOT_FOUND: 'EXCEL_TOKEN_NOT_FOUND',
  EXCEL_FIELD_INVALID: 'EXCEL_FIELD_INVALID',
  EXCEL_ORDER_NOT_FOUND: 'EXCEL_ORDER_NOT_FOUND',
  EXCEL_ORDER_CONFLICT: 'EXCEL_ORDER_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode = (typeof apiErrorCodes)[keyof typeof apiErrorCodes];

type ApiErrorConfig = {
  code: ApiErrorCode;
  status: number;
  message: string;
  detail?: unknown;
};

export class ApiError extends Error {
  readonly code: ApiErrorCode;
  readonly status: number;
  readonly detail?: unknown;

  constructor({ code, status, message, detail }: ApiErrorConfig) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
    this.status = status;
    this.detail = detail;
  }
}

export function createApiError(config: ApiErrorConfig): ApiError {
  return new ApiError(config);
}

export function isApiError(error: unknown): error is ApiError {
  return error instanceof ApiError;
}
