export const auditActions = {
  DELETION_REQUEST_APPROVE: 'DELETION_REQUEST_APPROVE',
  DELETION_REQUEST_CREATE: 'DELETION_REQUEST_CREATE',
  DELETION_REQUEST_REJECT: 'DELETION_REQUEST_REJECT',
  DETAIL_CREATE: 'DETAIL_CREATE',
  DETAIL_CREATE_DIRECT: 'DETAIL_CREATE_DIRECT',
  DETAIL_UPDATE: 'DETAIL_UPDATE',
  INVOICE_CREATE: 'INVOICE_CREATE',
  INVOICE_DELETE: 'INVOICE_DELETE',
  INVOICE_IMPORT: 'INVOICE_IMPORT',
  INVOICE_REMATCH: 'INVOICE_REMATCH',
  INVOICE_REMATCH_APPLY: 'INVOICE_REMATCH_APPLY',
  INVOICE_UPDATE_DATES: 'INVOICE_UPDATE_DATES',
  ORDER_ADD: 'ORDER_ADD',
  ORDER_DELETE: 'ORDER_DELETE',
  ORDER_TRANSFER_BALANCE: 'ORDER_TRANSFER_BALANCE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  RECEIPT_CREATE: 'RECEIPT_CREATE',
  RECEIPT_MARK_RECEIVED: 'RECEIPT_MARK_RECEIVED',
  RECEIPT_UPDATE: 'RECEIPT_UPDATE',
  SWIFT_CREATE: 'SWIFT_CREATE',
  SWIFT_DELETE: 'SWIFT_DELETE',
  SYSTEM_SETTINGS_AUDIT_EXPORT: 'SYSTEM_SETTINGS_AUDIT_EXPORT',
  SYSTEM_SETTINGS_UPDATE: 'SYSTEM_SETTINGS_UPDATE',
} as const;

export type AuditAction = (typeof auditActions)[keyof typeof auditActions];

export const auditTargetTypes = {
  DELETION_REQUEST: 'DELETION_REQUEST',
  DETAIL: 'DETAIL',
  INVOICE: 'INVOICE',
  ORDER: 'ORDER',
  RECEIPT: 'RECEIPT',
  SWIFT: 'SWIFT',
  SYSTEM_SETTING: 'SYSTEM_SETTING',
} as const;

export type AuditTargetType = (typeof auditTargetTypes)[keyof typeof auditTargetTypes];
