import nextJest from 'next/jest.js';

const createJestConfig = nextJest({
  dir: './',
});

const customJestConfig = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  testPathIgnorePatterns: ['/node_modules/', '/.next/', '/tests/e2e/'],
  modulePathIgnorePatterns: ['<rootDir>/.next/standalone/'],
  collectCoverageFrom: [
    'src/components/workspace/modules/invoices/hooks/use-invoice-view-state.ts',
    'src/components/workspace/modules/invoices/hooks/use-invoice-actions.ts',
    'src/components/workspace/modules/customers/hooks/use-customer-forms.ts',
    'src/components/workspace/modules/customers/hooks/use-customer-actions.ts',
    'src/components/workspace/modules/receipts/hooks/use-receipt-actions.ts',
    'src/components/workspace/modules/details/hooks/use-detail-actions.ts',
    'src/components/workspace/modules/swifts/hooks/use-swift-actions.ts',
    'src/components/workspace/modules/deletions/hooks/use-deletion-actions.ts',
    'src/components/workspace/modules/settings/hooks/use-settings-forms.ts',
    'src/components/workspace/modules/settings/hooks/use-settings-actions.ts',
    'src/components/workspace/modules/settings/read-model.ts',
    'src/components/workspace/modules/settings/page-view-model.ts',
    'src/components/workspace/modules/users/hooks/use-user-actions.ts',
    'src/lib/deletion-service.ts',
    'src/lib/settings-read-service.ts',
    'src/lib/settings-write-service.ts',
    'src/lib/swift-service.ts',
    'src/lib/receipt-service.ts',
    'src/lib/detail-service.ts',
    'src/lib/auth-service.ts',
    'src/lib/customer-service.ts',
    'src/lib/customer-fix-service.ts',
    'src/lib/customer-read-service.ts',
    'src/lib/init-service.ts',
    'src/lib/invoice-service.ts',
    'src/lib/invoice-write.ts',
    'src/lib/invoice-read-service.ts',
    'src/lib/report-service.ts',
    'src/lib/http-body.ts',
    'src/lib/rate-limit.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 65,
      functions: 84,
      lines: 83,
      statements: 81,
    },
    './src/components/workspace/modules/invoices/hooks/use-invoice-view-state.ts': {
      branches: 60,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/components/workspace/modules/invoices/hooks/use-invoice-actions.ts': {
      branches: 75,
      functions: 90,
      lines: 85,
      statements: 85,
    },
    './src/components/workspace/modules/customers/hooks/use-customer-forms.ts': {
      branches: 45,
      functions: 35,
      lines: 70,
      statements: 70,
    },
    './src/components/workspace/modules/customers/hooks/use-customer-actions.ts': {
      branches: 60,
      functions: 81,
      lines: 70,
      statements: 70,
    },
    './src/components/workspace/modules/receipts/hooks/use-receipt-actions.ts': {
      branches: 45,
      functions: 100,
      lines: 80,
      statements: 79,
    },
    './src/components/workspace/modules/details/hooks/use-detail-actions.ts': {
      branches: 45,
      functions: 100,
      lines: 85,
      statements: 84,
    },
    './src/components/workspace/modules/swifts/hooks/use-swift-actions.ts': {
      branches: 45,
      functions: 100,
      lines: 85,
      statements: 83,
    },
    './src/components/workspace/modules/deletions/hooks/use-deletion-actions.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/components/workspace/modules/settings/hooks/use-settings-forms.ts': {
      branches: 60,
      functions: 100,
      lines: 90,
      statements: 90,
    },
    './src/components/workspace/modules/settings/hooks/use-settings-actions.ts': {
      branches: 55,
      functions: 98,
      lines: 80,
      statements: 80,
    },
    './src/components/workspace/modules/settings/read-model.ts': {
      branches: 65,
      functions: 90,
      lines: 85,
      statements: 85,
    },
    './src/components/workspace/modules/settings/page-view-model.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/components/workspace/modules/users/hooks/use-user-actions.ts': {
      branches: 50,
      functions: 100,
      lines: 88,
      statements: 85,
    },
    './src/lib/deletion-service.ts': {
      branches: 50,
      functions: 70,
      lines: 60,
      statements: 60,
    },
    './src/lib/settings-read-service.ts': {
      branches: 80,
      functions: 97,
      lines: 95,
      statements: 90,
    },
    './src/lib/settings-write-service.ts': {
      branches: 65,
      functions: 80,
      lines: 75,
      statements: 75,
    },
    './src/lib/swift-service.ts': {
      branches: 40,
      functions: 70,
      lines: 60,
      statements: 60,
    },
    './src/lib/receipt-service.ts': {
      branches: 30,
      functions: 45,
      lines: 42,
      statements: 42,
    },
    './src/lib/detail-service.ts': {
      branches: 30,
      functions: 45,
      lines: 42,
      statements: 42,
    },
    './src/lib/auth-service.ts': {
      branches: 45,
      functions: 90,
      lines: 70,
      statements: 70,
    },
    './src/lib/customer-service.ts': {
      branches: 50,
      functions: 55,
      lines: 65,
      statements: 65,
    },
    './src/lib/customer-read-service.ts': {
      branches: 80,
      functions: 100,
      lines: 97,
      statements: 97,
    },
    './src/lib/customer-fix-service.ts': {
      branches: 55,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/lib/init-service.ts': {
      branches: 55,
      functions: 65,
      lines: 70,
      statements: 70,
    },
    './src/lib/invoice-service.ts': {
      branches: 50,
      functions: 55,
      lines: 60,
      statements: 60,
    },
    './src/lib/invoice-read-service.ts': {
      branches: 85,
      functions: 100,
      lines: 97,
      statements: 97,
    },
    './src/lib/invoice-write.ts': {
      branches: 60,
      functions: 90,
      lines: 80,
      statements: 80,
    },
    './src/lib/report-service.ts': {
      branches: 80,
      functions: 100,
      lines: 90,
      statements: 90,
    },
    './src/lib/http-body.ts': {
      branches: 80,
      functions: 100,
      lines: 90,
      statements: 90,
    },
    './src/lib/rate-limit.ts': {
      branches: 70,
      functions: 100,
      lines: 95,
      statements: 95,
    },
  },
};

export default createJestConfig(customJestConfig);
