'use client';

import React, { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import type { ReceiptGeneratorLayoutData } from '@/lib/receipt-generator-layout';

export type ReceiptCanvasHandle = {
  exportBlob: () => Promise<Blob>;
};

type ReceiptCanvasProps = {
  layout: ReceiptGeneratorLayoutData;
  receiverSignature: string | null;
  payerSignature: string | null;
  className?: string;
};

async function loadImage(dataUrl: string | null): Promise<HTMLImageElement | null> {
  if (!dataUrl) return null;
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = reject;
    image.src = dataUrl;
  });
}

function drawLine(ctx: CanvasRenderingContext2D, x1: number, y1: number, x2: number, y2: number) {
  ctx.beginPath();
  ctx.moveTo(x1, y1);
  ctx.lineTo(x2, y2);
  ctx.stroke();
}

async function drawReceiptCanvas(
  canvas: HTMLCanvasElement,
  layout: ReceiptGeneratorLayoutData,
  receiverSignature: string | null,
  payerSignature: string | null,
) {
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const [receiverImage, payerImage] = await Promise.all([
    loadImage(receiverSignature),
    loadImage(payerSignature),
  ]);

  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.strokeStyle = '#111827';
  ctx.fillStyle = '#111827';
  ctx.lineWidth = 2;
  ctx.font = '28px Arial';
  ctx.fillText('RECU / RECEIPT', 430, 70);

  ctx.font = '18px Arial';
  ctx.fillText(`No.: ${layout.receiptNo}`, 60, 120);
  ctx.fillText(`Date: ${layout.dateText}`, 920, 120);

  drawLine(ctx, 40, 150, 1160, 150);

  const rows = [
    ['Order No.', layout.orderNo || '-'],
    ['Invoice No.', layout.invNo || '-'],
    ['Client', layout.clientName || '-'],
    ['Tel', layout.clientTel || '-'],
    ['Amount (USD)', `$${layout.usdAmount.toFixed(2)}`],
    ['Amount in words', layout.amountInWords],
    ['Motif', layout.motif],
    ['Balance before', layout.balanceBefore === null ? '-' : `$${layout.balanceBefore.toFixed(2)}`],
    ['Balance after', layout.balanceAfter === null ? '-' : `$${layout.balanceAfter.toFixed(2)}`],
    ['Reste a payer', layout.resteAPayer],
    ['Received by', layout.receivedBy],
  ];

  let y = 190;
  rows.forEach(([label, value], index) => {
    ctx.font = 'bold 18px Arial';
    ctx.fillText(label, 60, y);
    ctx.font = '18px Arial';
    const wrapped = String(value).match(/.{1,70}(\s|$)|\S+?(\s|$)/g) || [String(value)];
    let innerY = y;
    wrapped.forEach((line) => {
      ctx.fillText(line.trim(), 310, innerY);
      innerY += 28;
    });
    y = Math.max(y + 42, innerY + 14);
    if (index < rows.length - 1) {
      drawLine(ctx, 60, y - 12, 1140, y - 12);
    }
  });

  const sigTop = 1180;
  ctx.font = 'bold 18px Arial';
  ctx.fillText('Recu par / Receiver signature', 80, sigTop);
  ctx.fillText('Signature du payeur / Payer signature', 660, sigTop);
  ctx.strokeRect(80, sigTop + 20, 420, 160);
  ctx.strokeRect(660, sigTop + 20, 420, 160);

  if (receiverImage) {
    ctx.drawImage(receiverImage, 95, sigTop + 35, 390, 130);
  }
  if (payerImage) {
    ctx.drawImage(payerImage, 675, sigTop + 35, 390, 130);
  }

  ctx.font = '16px Arial';
  ctx.fillText('Generated by Trading Ledger System', 60, 1610);
}

export const ReceiptCanvas = forwardRef<ReceiptCanvasHandle, ReceiptCanvasProps>(function ReceiptCanvas(
  { layout, receiverSignature, payerSignature, className = '' },
  ref,
) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    drawReceiptCanvas(canvas, layout, receiverSignature, payerSignature).catch((error) => {
      console.error('Draw receipt canvas failed:', error);
    });
  }, [layout, receiverSignature, payerSignature]);

  useImperativeHandle(ref, () => ({
    exportBlob: async () => {
      const canvas = canvasRef.current;
      if (!canvas) {
        throw new Error('Receipt canvas unavailable');
      }
      await drawReceiptCanvas(canvas, layout, receiverSignature, payerSignature);
      const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
      if (!blob) {
        throw new Error('Receipt export failed');
      }
      return blob;
    },
  }), [layout, receiverSignature, payerSignature]);

  return (
    <div className={`rounded-xl border bg-white p-3 shadow-sm ${className}`}>
      <canvas
        ref={canvasRef}
        width={1200}
        height={1650}
        className="h-auto w-full rounded-lg bg-white"
      />
    </div>
  );
});
