ALTER TABLE `UploadedAsset`
  MODIFY `category` ENUM('RECEIPT_DIRECT', 'RECEIPT_OCR', 'DETAIL_OCR', 'SWIFT_OCR', 'RECEIPT_GENERATOR_FINAL', 'RECEIPT_GENERATOR_SIGNATURE', 'AGENT_FILE', 'CUSTOMER_FILE') NOT NULL,
  MODIFY `attachedType` ENUM('RECEIPT', 'DETAIL', 'SWIFT', 'RECEIPT_GENERATOR_SESSION', 'PAYMENT_AGENT_FILE', 'CUSTOMER_FILE') NULL;
