export * from '@/components/workspace/modules/dashboard';
export * from '@/components/workspace/modules/invoices';
export * from '@/components/workspace/modules/receipts';
export * from '@/components/workspace/modules/details';
export * from '@/components/workspace/modules/swifts';
export * from '@/components/workspace/modules/deletions';
export * from '@/components/workspace/modules/users';
export * from '@/components/workspace/modules/customers';
export * from '@/components/workspace/modules/settings';
